# Generated by Django 4.0.1 on 2022-07-14 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challange', '0003_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='isadmin',
            field=models.BooleanField(default=False),
        ),
    ]
