# Generated by Django 4.0.1 on 2022-07-14 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challange', '0006_question_answer_question_order_useranswer_iscorrect_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('s', 'single'), ('m', 'multi')], default='s', max_length=1),
        ),
    ]
