# Generated by Django 4.0.1 on 2022-07-15 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challange', '0007_question_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='howmany',
            field=models.IntegerField(default=5),
        ),
    ]
