# Generated by Django 4.0.1 on 2022-07-15 15:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('challange', '0008_tournament_howmany'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('all_answer', models.IntegerField()),
                ('all_answer_correct', models.IntegerField()),
                ('valid', models.BooleanField(default=False)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
